name: VulnScout CI bitbake-setup

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  vulnscout-ci:
    runs-on: [self-hosted, linux]
    steps:
      - name: Clean workspace
        run: |
          sudo rm -rf /media/qlehoux/actions-runner/_work/vulnscout_CI_demo/vulnscout_CI_demo/* || true
          sudo rm -rf /media/qlehoux/actions-runner/_work/vulnscout_CI_demo/vulnscout_CI_demo/.* || true
        continue-on-error: true

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Enable user namespace
        run: |
          sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Launch bitbake-setup init
        id: run_bitbake-setup
        run: |
          bitbake/bin/bitbake-setup \
          --setting default top-dir-name bitbake-build \
          init \
          --non-interactive \
          ./basic-config.conf.json \
          nodistro \
          machine/qemux86-64

      - name: Launch VulnScout CI with fail condition
        run: |
          export BB_ENV_PASSTHROUGH_ADDITIONS="VULNSCOUT_FAIL_CONDITION"
          export VULNSCOUT_FAIL_CONDITION="cvss >= 9.0"
          echo "BB_ENV_PASSTHROUGH_ADDITIONS: $BB_ENV_PASSTHROUGH_ADDITIONS"
          echo "VULNSCOUT_FAIL_CONDITION: $VULNSCOUT_FAIL_CONDITION"
          source bitbake-build/oe-nodistro-master/build/init-build-env
          echo "After sourcing - VULNSCOUT_FAIL_CONDITION: $VULNSCOUT_FAIL_CONDITION"
          bitbake core-image-minimal -c vulnscout_ci

      - name: Cleanup build artifacts
        if: always()
        run: |
          sudo chown -R qlehoux:qlehoux /media/qlehoux/actions-runner/_work/vulnscout_CI_demo/ || true
          sudo rm -rf bitbake-build || true