name: VulnScout CI bitbake-setup

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  vulnscout-ci:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Enable user namespace
        run: |
          sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Launch bitbake-setup init
        id: run_bitbake-setup
        run: |
          bitbake/bin/bitbake-setup \
          --setting default top-dir-name bitbake-build \
          init \
          --non-interactive \
          ./basic-config.conf.json \
          nodistro \
          machine/qemux86-64

      - name: Configure build environment
        run: |
          echo 'VULNSCOUT_FAIL_CONDITION = "cvss >= 9.0"' >> bitbake-build/oe-nodistro-master/build/conf/local.conf

      - name: Launch VulnScout CI with fail condition
        run: |
          source bitbake-build/oe-nodistro-master/build/init-build-env
          bitbake core-image-minimal -c vulnscout_ci