name: VulnScout CI cqfd +kas

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  vulnscout-ci:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable user namespaces
        run: |
          sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Install kas on the CI
        run: |
          which kas
          if [ $? -ne 0 ]; then
            pip3 install kas
          fi

      - name: Install cqfd on the CI
        run: |
          which cqfd
          if [ $? -ne 0 ]; then
            git clone https://github.com/savoirfairelinux/cqfd.git
            cd cqfd
            make install
          fi

      - name: Init cqfd container on the project
        run: cqfd init

      - name: Run vulnscout_ci
        id: run_cqfd
        run: cqfd -b vulnscout_ci
